# Generated by Django 5.1.3 on 2024-12-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='transactions',
            field=models.ManyToManyField(related_name='budget_items', to='transactions.transaction'),
        ),
    ]
