# Generated by Django 5.1.4 on 2024-12-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budgetitem_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking'), ('CREDIT CARD', 'Credit Card'), ('SAVINGS', 'Savings')], max_length=50),
        ),
    ]
