# Generated by Django 5.1.4 on 2024-12-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_alter_account_account_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING", "Checking"),
                    ("SAVINGS", "Savings"),
                    ("CREDIT CARD", "Credit Card"),
                ],
                max_length=50,
            ),
        ),
    ]
