# Generated by Django 5.1.4 on 2025-01-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0014_alter_account_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("SAVINGS", "Savings"),
                    ("CHECKING", "Checking"),
                    ("CREDIT CARD", "Credit Card"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                default="INCOME",
                max_length=7,
            ),
        ),
    ]
