[project]
name = "financeapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dependency>=0.0.3",
    "django>=5.1.4",
    "python-decouple>=3.8",
]
